import re

with open('static/script.js', 'r') as f:
    content = f.read()

# We need to completely rewrite the translations object.
translations_js = """  const translations = {
    en: {
      heading: "Understand Elections. Instantly.",
      subheading: "Ask anything about elections and get clear answers.",
      inputPlaceholder: "Ask about voting, registration, election steps...",
      welcomeText: "Hi! I'm your Election AI. Ask me anything about voting or the election process.",
      flowTitle: "Guided Election Flow",
      flowSubtitle: "Follow the journey from registration to results.",
      stepsTitle: "Election Steps",
      timelineTitle: "Election Timeline",
      readyTitle: "Am I Ready to Vote?",
      faqTitle: "Frequently Asked Questions",
      quizTitle: "Test Your Knowledge",
      guideTitle: "How to Vote — Step by Step",
      
      flowStep1Title: "Register",
      flowStep1Desc: "Complete your voter registration with your local election office or online portal.",
      flowStep2Title: "Research",
      flowStep2Desc: "Learn about candidates, ballot measures, and your polling location.",
      flowStep3Title: "Vote",
      flowStep3Desc: "Cast your ballot — in person, by mail, or through early voting.",
      flowStep4Title: "Results",
      flowStep4Desc: "Ballots are counted and certified. Official results are announced.",

      step1Title: "Voter Registration",
      step1Desc: "Verify your eligibility, gather required documents, and submit your registration before the deadline.",
      step2Title: "Primary Elections",
      step2Desc: "Political parties hold primaries or caucuses to select their candidates for the general election.",
      step3Title: "Campaign Season",
      step3Desc: "Candidates present platforms, participate in debates, and campaign to win voter support.",
      step4Title: "Casting Ballots",
      step4Desc: "Vote at your designated polling station, via mail-in ballot, or through early voting options.",
      step5Title: "Vote Counting",
      step5Desc: "Election officials tally all ballots — including absentee, mail-in, and provisional votes.",
      step6Title: "Certification",
      step6Desc: "Results are officially certified after thorough review, audits, and any necessary recounts.",

      readyQ1: "Are you 18 years or older?",
      readyQ2: "Are you a registered voter?",
      readyQ3: "Do you have a valid voter ID?",
      readyQ4: "Do you know your polling station?",
      readyBtn: "Check My Readiness",
      readySubtitle: "Answer a few questions to check your readiness.",

      navHome: "Home",
      navFlow: "Flow",
      navSteps: "Steps",
      navTimeline: "Timeline",
      navReady: "Am I Ready?",
      navFAQ: "FAQ",
      navQuiz: "Quiz",
      navGuide: "Guide",

      faqSubtitle: "Quick answers to common election questions.",
      faqQ1: "What documents do I need to register?",
      faqA1: "Typically, you need a government-issued photo ID (driver's license, passport) and proof of address (utility bill, bank statement). Requirements vary by state/country.",
      faqQ2: "Can I vote if I'm abroad?",
      faqA2: "Yes — most countries allow absentee or overseas voting. You'll need to register in advance and request an absentee ballot from your home jurisdiction.",
      faqQ3: "What is early voting?",
      faqA3: "Early voting allows you to cast your ballot before the official Election Day, often at designated locations during a specified period (usually 1–2 weeks before).",
      faqQ4: "How are votes counted?",
      faqA4: "Ballots are collected from polling stations and processed by election officials using optical scanners or manual tallying. Results are verified through audits before certification.",
      faqQ5: "What if I make a mistake on my ballot?",
      faqA5: "If you make a mistake, you can usually request a replacement ballot at the polling station. For mail-in ballots, contact your local election office for guidance before the deadline.",

      quizSubtitle: "A quick quiz on election fundamentals.",

      guideSubtitle: "Your complete beginner-friendly walkthrough.",
      guideStep1Title: "Check Eligibility",
      guideStep1Desc: "Confirm you meet the age, citizenship, and residency requirements for your jurisdiction.",
      guideStep2Title: "Register to Vote",
      guideStep2Desc: "Visit your local election office or use the online portal. Have your ID and proof of address ready.",
      guideStep3Title: "Find Your Polling Station",
      guideStep3Desc: "Use your government's polling station locator tool to find your designated voting place.",
      guideStep4Title: "Prepare Your Documents",
      guideStep4Desc: "Gather your voter ID, registration confirmation, and any other required identification.",
      guideStep5Title: "Cast Your Vote",
      guideStep5Desc: "Visit your polling station on Election Day. Follow the instructions, mark your ballot, and submit it.",
      guideStep6Title: "Verify & Track",
      guideStep6Desc: "Some jurisdictions let you track your ballot online to confirm it was received and counted.",
      
      stepsSubtitle: "A deeper look at every stage of the process.",
      timelineSubtitle: "Key milestones in a typical election cycle.",
      
      quizQ0: "1. What is the minimum voting age in most democracies?",
      quizQ0Opt0: "16",
      quizQ0Opt1: "18",
      quizQ0Opt2: "21",
      quizQ0Opt3: "25",
      quizQ1: "2. Which document is most commonly required at polling stations?",
      quizQ1Opt0: "Library card",
      quizQ1Opt1: "Voter ID / Photo ID",
      quizQ1Opt2: "Social media account",
      quizQ1Opt3: "Birth certificate",
      quizQ2: "3. What is an 'absentee ballot'?",
      quizQ2Opt0: "A ballot cast at a polling station",
      quizQ2Opt1: "A ballot cast by mail for those who can't vote in person",
      quizQ2Opt2: "A blank ballot",
      quizQ2Opt3: "A ballot that was not counted",
      quizSubmitBtn: "Submit Quiz",

      suggestions: [
        "What is voting?",
        "Steps in election process",
        "How to register as a voter",
        "What happens after voting?"
      ]
    },
    hi: {
      heading: "चुनाव को तुरंत समझें",
      subheading: "चुनाव के बारे में कुछ भी पूछें और स्पष्ट उत्तर पाएं",
      inputPlaceholder: "मतदान, पंजीकरण या चुनाव प्रक्रिया के बारे में पूछें...",
      welcomeText: "नमस्ते! मैं आपका चुनाव एआई हूँ। मतदान या चुनाव प्रक्रिया के बारे में कुछ भी पूछें।",
      flowTitle: "निर्देशित चुनाव प्रवाह",
      flowSubtitle: "पंजीकरण से परिणाम तक की यात्रा का पालन करें।",
      stepsTitle: "चुनाव के चरण",
      timelineTitle: "चुनाव समयरेखा",
      readyTitle: "क्या मैं मतदान के लिए तैयार हूँ?",
      faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
      quizTitle: "अपने ज्ञान का परीक्षण करें",
      guideTitle: "मतदान कैसे करें - चरण दर चरण",

      flowStep1Title: "पंजीकरण",
      flowStep1Desc: "अपने स्थानीय चुनाव कार्यालय या ऑनलाइन पोर्टल के साथ अपना मतदाता पंजीकरण पूरा करें।",
      flowStep2Title: "अनुसंधान",
      flowStep2Desc: "उम्मीदवारों, मतपत्र उपायों और अपने मतदान स्थान के बारे में जानें।",
      flowStep3Title: "मतदान",
      flowStep3Desc: "अपना वोट डालें - व्यक्तिगत रूप से, मेल द्वारा, या प्रारंभिक मतदान के माध्यम से।",
      flowStep4Title: "परिणाम",
      flowStep4Desc: "मतपत्रों की गिनती और प्रमाणित किया जाता है। आधिकारिक परिणाम घोषित किए जाते हैं।",

      step1Title: "मतदाता पंजीकरण",
      step1Desc: "अपनी पात्रता सत्यापित करें, आवश्यक दस्तावेज एकत्र करें, और समय सीमा से पहले अपना पंजीकरण जमा करें।",
      step2Title: "प्राथमिक चुनाव",
      step2Desc: "राजनीतिक दल आम चुनाव के लिए अपने उम्मीदवारों का चयन करने के लिए प्राइमरी या कॉकस आयोजित करते हैं।",
      step3Title: "अभियान का मौसम",
      step3Desc": "उम्मीदवार मंच प्रस्तुत करते हैं, बहस में भाग लेते हैं, और मतदाता समर्थन जीतने के लिए अभियान चलाते हैं।",
      step4Title: "मतदान",
      step4Desc: "अपने निर्दिष्ट मतदान केंद्र पर, मेल-इन बैलेट के माध्यम से, या शुरुआती मतदान विकल्पों के माध्यम से मतदान करें।",
      step5Title: "मतगणना",
      step5Desc: "चुनाव अधिकारी सभी मतपत्रों की गिनती करते हैं - जिसमें अनुपस्थित, मेल-इन और अनंतिम वोट शामिल हैं।",
      step6Title: "प्रमाणीकरण",
      step6Desc: "गहन समीक्षा, ऑडिट और किसी भी आवश्यक पुनर्गणना के बाद आधिकारिक तौर पर परिणाम प्रमाणित किए जाते हैं।",

      readyQ1: "क्या आप 18 वर्ष या उससे अधिक उम्र के हैं?",
      readyQ2: "क्या आप एक पंजीकृत मतदाता हैं?",
      readyQ3: "क्या आपके पास वैध मतदाता पहचान पत्र है?",
      readyQ4: "क्या आप अपना मतदान केंद्र जानते हैं?",
      readyBtn: "मेरी तैयारी की जाँच करें",
      readySubtitle: "अपनी तैयारी की जांच करने के लिए कुछ सवालों के जवाब दें।",

      navHome: "होम",
      navFlow: "प्रवाह",
      navSteps: "चरण",
      navTimeline: "समयरेखा",
      navReady: "क्या मैं तैयार हूँ?",
      navFAQ: "सामान्य प्रश्न",
      navQuiz: "प्रश्नोत्तरी",
      navGuide: "मार्गदर्शिका",

      faqSubtitle: "सामान्य चुनाव प्रश्नों के त्वरित उत्तर।",
      faqQ1: "पंजीकरण के लिए मुझे किन दस्तावेजों की आवश्यकता है?",
      faqA1: "आमतौर पर, आपको सरकार द्वारा जारी फोटो आईडी (ड्राइवर का लाइसेंस, पासपोर्ट) और पते के प्रमाण (उपयोगिता बिल, बैंक स्टेटमेंट) की आवश्यकता होती है। आवश्यकताएं राज्य/देश के अनुसार भिन्न होती हैं।",
      faqQ2: "क्या मैं विदेश में होने पर मतदान कर सकता हूँ?",
      faqA2: "हाँ - अधिकांश देश अनुपस्थित या विदेशी मतदान की अनुमति देते हैं। आपको अग्रिम रूप से पंजीकरण करना होगा और अपने गृह क्षेत्र से अनुपस्थित मतपत्र का अनुरोध करना होगा।",
      faqQ3: "शुरुआती मतदान क्या है?",
      faqA3: "प्रारंभिक मतदान आपको आधिकारिक चुनाव दिवस से पहले, अक्सर निर्दिष्ट अवधि के दौरान (आमतौर पर 1-2 सप्ताह पहले) निर्दिष्ट स्थानों पर अपना मत डालने की अनुमति देता है।",
      faqQ4: "वोटों की गिनती कैसे होती है?",
      faqA4: "मतदान केंद्रों से मतपत्र एकत्र किए जाते हैं और चुनाव अधिकारियों द्वारा ऑप्टिकल स्कैनर या मैनुअल टैलीइंग का उपयोग करके संसाधित किए जाते हैं। प्रमाणीकरण से पहले ऑडिट के माध्यम से परिणामों को सत्यापित किया जाता है।",
      faqQ5: "अगर मैं अपने मतपत्र पर गलती कर दूं तो क्या होगा?",
      faqA5: "यदि आप कोई गलती करते हैं, तो आप आमतौर पर मतदान केंद्र पर प्रतिस्थापन मतपत्र का अनुरोध कर सकते हैं। मेल-इन बैलेट के लिए, समय सीमा से पहले मार्गदर्शन के लिए अपने स्थानीय चुनाव कार्यालय से संपर्क करें।",

      quizSubtitle: "चुनाव के मूल सिद्धांतों पर एक त्वरित प्रश्नोत्तरी।",

      guideSubtitle: "आपका संपूर्ण शुरुआत के अनुकूल वॉकथ्रू।",
      guideStep1Title: "पात्रता जांचें",
      guideStep1Desc: "पुष्टि करें कि आप अपने अधिकार क्षेत्र के लिए आयु, नागरिकता और निवास आवश्यकताओं को पूरा करते हैं।",
      guideStep2Title: "मतदान के लिए पंजीकरण करें",
      guideStep2Desc: "अपने स्थानीय चुनाव कार्यालय पर जाएं या ऑनलाइन पोर्टल का उपयोग करें। अपना आईडी और पते का प्रमाण तैयार रखें।",
      guideStep3Title: "अपना मतदान केंद्र खोजें",
      guideStep3Desc": "अपना निर्दिष्ट मतदान स्थान खोजने के लिए अपनी सरकार के मतदान केंद्र लोकेटर टूल का उपयोग करें।",
      guideStep4Title: "अपने दस्तावेज़ तैयार करें",
      guideStep4Desc: "अपना वोटर आईडी, पंजीकरण पुष्टिकरण, और कोई अन्य आवश्यक पहचान एकत्र करें।",
      guideStep5Title: "अपना वोट डालें",
      guideStep5Desc: "चुनाव के दिन अपने मतदान केंद्र पर जाएं। निर्देशों का पालन करें, अपने मतपत्र को चिह्नित करें, और इसे जमा करें।",
      guideStep6Title: "सत्यापित करें और ट्रैक करें",
      guideStep6Desc: "कुछ क्षेत्राधिकार आपको यह पुष्टि करने के लिए ऑनलाइन अपने मतपत्र को ट्रैक करने देते हैं कि यह प्राप्त हुआ और गिना गया।",

      stepsSubtitle: "प्रक्रिया के हर चरण पर एक गहरी नज़र।",
      timelineSubtitle: "एक विशिष्ट चुनाव चक्र में मुख्य मील के पत्थर।",
      
      quizQ0: "1. अधिकांश लोकतंत्रों में मतदान की न्यूनतम आयु क्या है?",
      quizQ0Opt0: "16",
      quizQ0Opt1: "18",
      quizQ0Opt2: "21",
      quizQ0Opt3: "25",
      quizQ1: "2. मतदान केंद्रों पर आमतौर पर कौन सा दस्तावेज़ आवश्यक होता है?",
      quizQ1Opt0: "लाइब्रेरी कार्ड",
      quizQ1Opt1: "वोटर आईडी / फोटो आईडी",
      quizQ1Opt2: "सोशल मीडिया अकाउंट",
      quizQ1Opt3: "जन्म प्रमाण पत्र",
      quizQ2: "3. 'अनुपस्थित मतपत्र' क्या है?",
      quizQ2Opt0: "मतदान केंद्र पर डाला गया मतपत्र",
      quizQ2Opt1: "उन लोगों के लिए मेल द्वारा डाला गया मतपत्र जो व्यक्तिगत रूप से मतदान नहीं कर सकते",
      quizQ2Opt2: "एक खाली मतपत्र",
      quizQ2Opt3: "एक मतपत्र जिसकी गिनती नहीं की गई थी",
      quizSubmitBtn: "प्रश्नोत्तरी सबमिट करें",

      suggestions: [
        "मतदान क्या है?",
        "चुनाव प्रक्रिया के चरण",
        "मतदाता के रूप में पंजीकरण कैसे करें",
        "मतदान के बाद क्या होता है?"
      ]
    },
    mr: {
      heading: "निवडणुका लगेच समजा",
      subheading: "निवडणुकांबद्दल काहीही विचारा आणि स्पष्ट उत्तर मिळवा",
      inputPlaceholder: "मतदान, नोंदणी किंवा निवडणूक प्रक्रियेबद्दल विचारा...",
      welcomeText: "नमस्कार! मी तुमचा निवडणूक AI आहे. मतदान किंवा निवडणूक प्रक्रियेबद्दल काहीही विचारा.",
      flowTitle: "मार्गदर्शित निवडणूक प्रवाह",
      flowSubtitle: "नोंदणीपासून निकालापर्यंतच्या प्रवासाचे अनुसरण करा.",
      stepsTitle: "निवडणुकीचे टप्पे",
      timelineTitle: "निवडणूक वेळापत्रक",
      readyTitle: "मी मतदानासाठी तयार आहे का?",
      faqTitle: "वारंवार विचारले जाणारे प्रश्न",
      quizTitle: "तुमच्या ज्ञानाची चाचणी घ्या",
      guideTitle: "मतदान कसे करावे - टप्प्याटप्प्याने",

      flowStep1Title: "नोंदणी करा",
      flowStep1Desc: "तुमच्या स्थानिक निवडणूक कार्यालयात किंवा ऑनलाइन पोर्टलवर तुमची मतदार नोंदणी पूर्ण करा.",
      flowStep2Title: "संशोधन",
      flowStep2Desc: "उमेदवार, मतपत्रिका उपाय आणि तुमचे मतदान केंद्र याबद्दल जाणून घ्या.",
      flowStep3Title: "मतदान",
      flowStep3Desc: "तुमचे मत द्या — वैयक्तिकरित्या, टपालाने किंवा लवकर मतदानाद्वारे.",
      flowStep4Title: "निकाल",
      flowStep4Desc: "मतपत्रिका मोजल्या जातात आणि प्रमाणित केल्या जातात. अधिकृत निकाल जाहीर केले जातात.",

      step1Title: "मतदार नोंदणी",
      step1Desc: "तुमची पात्रता सत्यापित करा, आवश्यक कागदपत्रे गोळा करा आणि अंतिम मुदतीपूर्वी तुमची नोंदणी सबमिट करा.",
      step2Title: "प्राथमिक निवडणुका",
      step2Desc: "राजकीय पक्ष सार्वत्रिक निवडणुकीसाठी त्यांचे उमेदवार निवडण्यासाठी प्राथमिक किंवा कॉकस आयोजित करतात.",
      step3Title: "प्रचार हंगाम",
      step3Desc: "उमेदवार व्यासपीठ सादर करतात, वादविवादांमध्ये भाग घेतात आणि मतदारांचा पाठिंबा मिळवण्यासाठी प्रचार करतात.",
      step4Title: "मतदान करणे",
      step4Desc: "तुमच्या नियुक्त केलेल्या मतदान केंद्रावर, मेल-इन मतपत्रिकेद्वारे किंवा लवकर मतदान पर्यायांद्वारे मतदान करा.",
      step5Title: "मतमोजणी",
      step5Desc: "निवडणूक अधिकारी अनुपस्थित, मेल-इन आणि तात्पुरत्या मतांसह सर्व मतपत्रिका मोजतात.",
      step6Title: "प्रमाणन",
      step6Desc: "सखोल पुनरावलोकन, ऑडिट आणि कोणत्याही आवश्यक पुनर्मोजणीनंतर अधिकृतपणे निकाल प्रमाणित केले जातात.",

      readyQ1: "तुम्ही १८ वर्षे किंवा त्याहून अधिक वयाचे आहात का?",
      readyQ2: "तुम्ही नोंदणीकृत मतदार आहात का?",
      readyQ3: "तुमच्याकडे वैध मतदार ओळखपत्र आहे का?",
      readyQ4: "तुम्हाला तुमचे मतदान केंद्र माहीत आहे का?",
      readyBtn: "माझी तयारी तपासा",
      readySubtitle: "तुमची तयारी तपासण्यासाठी काही प्रश्नांची उत्तरे द्या.",

      navHome: "मुख्यपृष्ठ",
      navFlow: "प्रवाह",
      navSteps: "टप्पे",
      navTimeline: "वेळापत्रक",
      navReady: "मी तयार आहे का?",
      navFAQ: "नेहमी विचारले जाणारे प्रश्न",
      navQuiz: "प्रश्नोत्तरी",
      navGuide: "मार्गदर्शक",

      faqSubtitle: "सामान्य निवडणूक प्रश्नांची जलद उत्तरे.",
      faqQ1: "नोंदणीसाठी मला कोणत्या कागदपत्रांची आवश्यकता आहे?",
      faqA1: "सामान्यतः, तुम्हाला सरकारने जारी केलेले फोटो आयडी (ड्रायव्हरचा परवाना, पासपोर्ट) आणि पत्त्याचा पुरावा (युटिलिटी बिल, बँक स्टेटमेंट) आवश्यक आहे. राज्यानुसार/देशानुसार आवश्यकता बदलतात.",
      faqQ2: "मी परदेशात असल्यास मतदान करू शकतो का?",
      faqA2: "होय — बहुतेक देश अनुपस्थित किंवा परदेशी मतदानाची परवानगी देतात. तुम्हाला अगोदर नोंदणी करावी लागेल आणि तुमच्या गृह अधिकारक्षेत्रातून अनुपस्थित मतपत्रिकेची विनंती करावी लागेल.",
      faqQ3: "लवकर मतदान म्हणजे काय?",
      faqA3: "लवकर मतदान तुम्हाला अधिकृत निवडणूक दिवसापूर्वी, बऱ्याचदा निर्दिष्ट कालावधीत (सामान्यतः १-२ आठवडे अगोदर) नियुक्त ठिकाणी मतदान करण्याची परवानगी देते.",
      faqQ4: "मते कशी मोजली जातात?",
      faqA4: "मतदान केंद्रांवरून मतपत्रिका गोळा केल्या जातात आणि निवडणूक अधिकाऱ्यांद्वारे ऑप्टिकल स्कॅनर किंवा मॅन्युअल टॅलींगचा वापर करून प्रक्रिया केली जाते. प्रमाणीकरणापूर्वी ऑडिटद्वारे निकालांची पडताळणी केली जाते.",
      faqQ5: "जर मी माझ्या मतपत्रिकेवर चूक केली तर काय होईल?",
      faqA5: "जर तुम्ही चूक केली, तर तुम्ही सहसा मतदान केंद्रावर बदली मतपत्रिकेची विनंती करू शकता. मेल-इन मतपत्रिकांसाठी, अंतिम मुदतीपूर्वी मार्गदर्शनासाठी तुमच्या स्थानिक निवडणूक कार्यालयाशी संपर्क साधा.",

      quizSubtitle: "निवडणुकीच्या मूलभूत गोष्टींवर एक द्रुत प्रश्नमंजुषा.",

      guideSubtitle: "तुमचे संपूर्ण नवशिक्या-अनुकूल मार्गदर्शक.",
      guideStep1Title: "पात्रता तपासा",
      guideStep1Desc: "तुम्ही तुमच्या अधिकारक्षेत्रासाठी वय, नागरिकत्व आणि निवास आवश्यकता पूर्ण करत असल्याची खात्री करा.",
      guideStep2Title: "मतदानासाठी नोंदणी करा",
      guideStep2Desc: "तुमच्या स्थानिक निवडणूक कार्यालयाला भेट द्या किंवा ऑनलाइन पोर्टल वापरा. तुमचा आयडी आणि पत्त्याचा पुरावा तयार ठेवा.",
      guideStep3Title: "तुमचे मतदान केंद्र शोधा",
      guideStep3Desc: "तुमचे नियुक्त मतदान ठिकाण शोधण्यासाठी तुमच्या सरकारच्या मतदान केंद्र लोकेटर टूलचा वापर करा.",
      guideStep4Title: "तुमची कागदपत्रे तयार करा",
      guideStep4Desc: "तुमचे मतदार ओळखपत्र, नोंदणी पुष्टीकरण आणि इतर कोणतीही आवश्यक ओळख गोळा करा.",
      guideStep5Title: "तुमचे मत द्या",
      guideStep5Desc: "निवडणुकीच्या दिवशी तुमच्या मतदान केंद्राला भेट द्या. सूचनांचे अनुसरण करा, तुमच्या मतपत्रिकेवर खूण करा आणि ती सबमिट करा.",
      guideStep6Title: "पडताळणी करा आणि ट्रॅक करा",
      guideStep6Desc: "काही अधिकारक्षेत्रे तुमची मतपत्रिका मिळाली आणि मोजली गेली याची पुष्टी करण्यासाठी ती ऑनलाइन ट्रॅक करू देतात.",

      stepsSubtitle: "प्रक्रियेच्या प्रत्येक टप्प्यावर एक सखोल नजर.",
      timelineSubtitle: "एका सामान्य निवडणूक चक्रातील प्रमुख टप्पे.",

      quizQ0: "1. बहुतांश लोकशाहीत मतदानाचे किमान वय किती असते?",
      quizQ0Opt0: "16",
      quizQ0Opt1: "18",
      quizQ0Opt2: "21",
      quizQ0Opt3: "25",
      quizQ1: "2. मतदान केंद्रांवर सामान्यतः कोणते कागदपत्र आवश्यक असते?",
      quizQ1Opt0: "लायब्ररी कार्ड",
      quizQ1Opt1: "मतदार ओळखपत्र / फोटो आयडी",
      quizQ1Opt2: "सोशल मीडिया खाते",
      quizQ1Opt3: "जन्म प्रमाणपत्र",
      quizQ2: "3. 'अनुपस्थित मतपत्रिका' म्हणजे काय?",
      quizQ2Opt0: "मतदान केंद्रावर टाकलेली मतपत्रिका",
      quizQ2Opt1: "जे वैयक्तिकरित्या मतदान करू शकत नाहीत त्यांच्यासाठी मेलद्वारे टाकलेली मतपत्रिका",
      quizQ2Opt2: "कोरी मतपत्रिका",
      quizQ2Opt3: "मोजली न गेलेली मतपत्रिका",
      quizSubmitBtn: "प्रश्नोत्तरी सबमिट करा",

      suggestions: [
        "मतदान म्हणजे काय?",
        "निवडणूक प्रक्रियेचे टप्पे",
        "मतदार म्हणून नोंदणी कशी करावी",
        "मतदानानंतर काय होते?"
      ]
    },
    ta: {
      heading: "தேர்தலை உடனே புரிந்துகொள்ளுங்கள்",
      subheading: "தேர்தல் பற்றிய எதையும் கேளுங்கள் மற்றும் தெளிவான பதில்களை பெறுங்கள்",
      inputPlaceholder: "வாக்களிப்பு, பதிவு அல்லது தேர்தல் படிகள் பற்றி கேளுங்கள்...",
      welcomeText: "வணக்கம்! நான் உங்கள் தேர்தல் AI. வாக்களிப்பு அல்லது தேர்தல் செயல்முறை பற்றி எதையும் கேளுங்கள்.",
      flowTitle: "வழிகாட்டப்பட்ட தேர்தல் ஓட்டம்",
      flowSubtitle: "பதிவு முதல் முடிவுகள் வரை பயணத்தைப் பின்பற்றுங்கள்.",
      stepsTitle: "தேர்தல் படிகள்",
      timelineTitle: "தேர்தல் காலவரிசை",
      readyTitle: "நான் வாக்களிக்க தயாரா?",
      faqTitle: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
      quizTitle: "உங்கள் அறிவை சோதிக்கவும்",
      guideTitle: "வாக்களிப்பது எப்படி - படிப்படியாக",

      flowStep1Title: "பதிவு",
      flowStep1Desc: "உங்கள் உள்ளூர் தேர்தல் அலுவலகம் அல்லது ஆன்லைன் போர்ட்டலில் உங்கள் வாக்காளர் பதிவை முடிக்கவும்.",
      flowStep2Title: "ஆராய்ச்சி",
      flowStep2Desc: "வேட்பாளர்கள், வாக்குச்சீட்டு நடவடிக்கைகள் மற்றும் உங்கள் வாக்குச்சாவடி இருப்பிடம் பற்றி அறியவும்.",
      flowStep3Title: "வாக்களிப்பு",
      flowStep3Desc: "நேரில், அஞ்சல் மூலம் அல்லது முன்கூட்டியே வாக்களிப்பதன் மூலம் உங்கள் வாக்கை பதிவு செய்யவும்.",
      flowStep4Title: "முடிவுகள்",
      flowStep4Desc: "வாக்குகள் எண்ணப்பட்டு சான்றளிக்கப்படுகின்றன. அதிகாரப்பூர்வ முடிவுகள் அறிவிக்கப்படுகின்றன.",

      step1Title: "வாக்காளர் பதிவு",
      step1Desc: "உங்கள் தகுதியைச் சரிபார்த்து, தேவையான ஆவணங்களைச் சேகரித்து, காலக்கெடுவுக்கு முன் உங்கள் பதிவைச் சமர்ப்பிக்கவும்.",
      step2Title: "முதன்மைத் தேர்தல்கள்",
      step2Desc: "பொதுத் தேர்தலுக்கான தங்கள் வேட்பாளர்களைத் தேர்ந்தெடுக்க அரசியல் கட்சிகள் முதன்மைத் தேர்தல்கள் அல்லது கூட்டங்களை நடத்துகின்றன.",
      step3Title: "பிரச்சாரப் பருவம்",
      step3Desc: "வேட்பாளர்கள் தளங்களை முன்வைக்கிறார்கள், விவாதங்களில் பங்கேற்கிறார்கள், மற்றும் வாக்காளர்களின் ஆதரவைப் பெற பிரச்சாரம் செய்கிறார்கள்.",
      step4Title: "வாக்களித்தல்",
      step4Desc: "உங்கள் நியமிக்கப்பட்ட வாக்குச்சாவடியில், அஞ்சல் வாக்குச்சீட்டு மூலம் அல்லது முன்கூட்டியே வாக்களிக்கும் விருப்பங்கள் மூலம் வாக்களிக்கவும்.",
      step5Title: "வாக்கு எண்ணிக்கை",
      step5Desc: "இல்லாதவர்கள், அஞ்சல் வாக்குகள் மற்றும் தற்காலிக வாக்குகள் உட்பட அனைத்து வாக்குகளையும் தேர்தல் அதிகாரிகள் எண்ணுகிறார்கள்.",
      step6Title: "சான்றளித்தல்",
      step6Desc: "முழுமையான மதிப்பாய்வு, தணிக்கைகள் மற்றும் தேவையான எந்தவொரு மறுஎண்ணிக்கைக்கும் பிறகு முடிவுகள் அதிகாரப்பூர்வமாக சான்றளிக்கப்படுகின்றன.",

      readyQ1: "உங்களுக்கு 18 வயது அல்லது அதற்கு மேற்பட்டதா?",
      readyQ2: "நீங்கள் பதிவு செய்யப்பட்ட வாக்காளரா?",
      readyQ3: "உங்களிடம் செல்லுபடியாகும் வாக்காளர் அடையாள அட்டை உள்ளதா?",
      readyQ4: "உங்கள் வாக்குச்சாவடி உங்களுக்குத் தெரியுமா?",
      readyBtn: "என் தயார்நிலையை சரிபார்க்கவும்",
      readySubtitle: "உங்கள் தயார்நிலையைச் சரிபார்க்க சில கேள்விகளுக்குப் பதிலளிக்கவும்.",

      navHome: "முகப்பு",
      navFlow: "ஓட்டம்",
      navSteps: "படிகள்",
      navTimeline: "காலவரிசை",
      navReady: "நான் தயாரா?",
      navFAQ: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
      navQuiz: "வினாடி வினா",
      navGuide: "வழிகாட்டி",

      faqSubtitle: "பொதுவான தேர்தல் கேள்விகளுக்கான விரைவான பதில்கள்.",
      faqQ1: "பதிவு செய்ய எனக்கு என்ன ஆவணங்கள் தேவை?",
      faqA1: "பொதுவாக, அரசாங்கத்தால் வழங்கப்பட்ட புகைப்பட அடையாள அட்டை (ஓட்டுநர் உரிமம், பாஸ்போர்ட்) மற்றும் முகவரிச் சான்று (மின்சாரக் கட்டணம், வங்கி அறிக்கை) தேவை. மாநிலம்/நாட்டைப் பொறுத்து தேவைகள் மாறுபடும்.",
      faqQ2: "நான் வெளிநாட்டில் இருந்தால் வாக்களிக்க முடியுமா?",
      faqA2: "ஆம் — பெரும்பாலான நாடுகள் இல்லாதவர்கள் அல்லது வெளிநாட்டு வாக்களிப்பை அனுமதிக்கின்றன. நீங்கள் முன்கூட்டியே பதிவு செய்து, உங்கள் சொந்த அதிகார வரம்பிலிருந்து வாக்களிக்காதோர் வாக்குச்சீட்டைக் கோர வேண்டும்.",
      faqQ3: "முன்கூட்டியே வாக்களிப்பது என்றால் என்ன?",
      faqA3: "அதிகாரப்பூர்வ தேர்தல் நாளுக்கு முன், பெரும்பாலும் ஒரு குறிப்பிட்ட காலப்பகுதியில் (பொதுவாக 1-2 வாரங்களுக்கு முன்) குறிப்பிட்ட இடங்களில் வாக்களிக்க முன்கூட்டியே வாக்களிப்பு உங்களை அனுமதிக்கிறது.",
      faqQ4: "வாக்குகள் எவ்வாறு எண்ணப்படுகின்றன?",
      faqA4: "வாக்குச்சாவடிகளில் இருந்து வாக்குகள் சேகரிக்கப்பட்டு, ஆப்டிகல் ஸ்கேனர்கள் அல்லது கையேடு எண்ணிக்கை மூலம் தேர்தல் அதிகாரிகளால் செயலாக்கப்படுகின்றன. சான்றளிப்பதற்கு முன் தணிக்கைகள் மூலம் முடிவுகள் சரிபார்க்கப்படுகின்றன.",
      faqQ5: "என் வாக்குச்சீட்டில் நான் தவறு செய்தால் என்ன செய்வது?",
      faqA5: "நீங்கள் தவறு செய்தால், வழக்கமாக வாக்குச்சாவடியில் மாற்று வாக்குச்சீட்டைக் கோரலாம். அஞ்சல் வாக்குகளுக்கு, காலக்கெடுவுக்கு முன் வழிகாட்டுதலுக்கு உங்கள் உள்ளூர் தேர்தல் அலுவலகத்தைத் தொடர்புகொள்ளவும்.",

      quizSubtitle: "தேர்தல் அடிப்படைகள் பற்றிய விரைவான வினாடி வினா.",

      guideSubtitle: "உங்கள் முழுமையான தொடக்கநிலையாளர் நட்பு ஒத்திகை.",
      guideStep1Title: "தகுதியைச் சரிபார்க்கவும்",
      guideStep1Desc: "உங்கள் அதிகார வரம்பிற்கான வயது, குடியுரிமை மற்றும் குடியிருப்புத் தேவைகளை நீங்கள் பூர்த்தி செய்கிறீர்கள் என்பதை உறுதிப்படுத்தவும்.",
      guideStep2Title: "வாக்களிக்கப் பதிவு செய்யவும்",
      guideStep2Desc: "உங்கள் உள்ளூர் தேர்தல் அலுவலகத்தைப் பார்வையிடவும் அல்லது ஆன்லைன் போர்ட்டலைப் பயன்படுத்தவும். உங்கள் ஐடி மற்றும் முகவரிச் சான்றை தயாராக வைத்திருக்கவும்.",
      guideStep3Title: "உங்கள் வாக்குச்சாவடியைக் கண்டறியவும்",
      guideStep3Desc: "உங்கள் நியமிக்கப்பட்ட வாக்களிக்கும் இடத்தைக் கண்டறிய உங்கள் அரசாங்கத்தின் வாக்குச்சாவடி லொக்கேட்டர் கருவியைப் பயன்படுத்தவும்.",
      guideStep4Title: "உங்கள் ஆவணங்களைத் தயாரிக்கவும்",
      guideStep4Desc: "உங்கள் வாக்காளர் அடையாள அட்டை, பதிவு உறுதிப்படுத்தல் மற்றும் தேவையான பிற அடையாளங்களைச் சேகரிக்கவும்.",
      guideStep5Title: "உங்கள் வாக்கைச் செலுத்தவும்",
      guideStep5Desc: "தேர்தல் நாளில் உங்கள் வாக்குச்சாவடியைப் பார்வையிடவும். வழிமுறைகளைப் பின்பற்றவும், உங்கள் வாக்குச்சீட்டைக் குறிக்கவும், அதைச் சமர்ப்பிக்கவும்.",
      guideStep6Title: "சரிபார்த்து கண்காணிக்கவும்",
      guideStep6Desc: "உங்கள் வாக்குச்சீட்டு பெறப்பட்டு எண்ணப்பட்டதை உறுதிப்படுத்த, அதை ஆன்லைனில் கண்காணிக்க சில அதிகார வரம்புகள் உங்களை அனுமதிக்கின்றன.",

      stepsSubtitle: "செயல்முறையின் ஒவ்வொரு கட்டத்தையும் ஆழமாகப் பாருங்கள்.",
      timelineSubtitle: "ஒரு வழக்கமான தேர்தல் சுழற்சியில் முக்கிய மைல்கற்கள்.",

      quizQ0: "1. பெரும்பாலான ஜனநாயக நாடுகளில் குறைந்தபட்ச வாக்களிக்கும் வயது என்ன?",
      quizQ0Opt0: "16",
      quizQ0Opt1: "18",
      quizQ0Opt2: "21",
      quizQ0Opt3: "25",
      quizQ1: "2. வாக்குச்சாவடிகளில் பொதுவாக எந்த ஆவணம் தேவைப்படுகிறது?",
      quizQ1Opt0: "நூலக அட்டை",
      quizQ1Opt1: "வாக்காளர் அடையாள அட்டை / புகைப்பட அடையாள அட்டை",
      quizQ1Opt2: "சமூக ஊடக கணக்கு",
      quizQ1Opt3: "பிறப்புச் சான்றிதழ்",
      quizQ2: "3. 'இல்லாதவர் வாக்குச்சீட்டு' என்றால் என்ன?",
      quizQ2Opt0: "வாக்குச்சாவடியில் போடப்பட்ட வாக்குச்சீட்டு",
      quizQ2Opt1: "நேரில் வாக்களிக்க முடியாதவர்களுக்காக அஞ்சல் மூலம் போடப்பட்ட வாக்குச்சீட்டு",
      quizQ2Opt2: "வெற்று வாக்குச்சீட்டு",
      quizQ2Opt3: "எண்ணப்படாத வாக்குச்சீட்டு",
      quizSubmitBtn: "வினாடி வினா சமர்ப்பி",

      suggestions: [
        "வாக்களிப்பு என்றால் என்ன?",
        "தேர்தல் செயல்முறையின் படிகள்",
        "வாக்காளராக பதிவு செய்வது எப்படி",
        "வாக்களித்த பிறகு என்ன நடக்கும்?"
      ]
    }
  };"""

# Use regex to find `const translations = { ... };` and replace it
# We know the object starts at `const translations = {` and ends before `const currentLanguage =`
pattern = re.compile(r'const translations = \{.*?\n  \};\n', re.DOTALL)
content = pattern.sub(translations_js + "\n", content)

with open('static/script.js', 'w') as f:
    f.write(content)
